@startuml
    skinparam componentStyle uml2

    !define ICONURL https://raw.githubusercontent.com/smartsdk/architecture-diagrams/smartsdk-template/dist
    !includeurl ICONURL/common.puml
    !includeurl ICONURL/fiware.puml
    !includeurl ICONURL/smartsdk.puml

    node "Fiware Cloud" as fc{
        rectangle "[Retrieving historical data]" as rhd{
            FIWARE(wcge,"Wire Cloud GE",component)
            FIWARE(imkge,"Identity Manager \n KeyRock GE",component)
            FIWARE(cbdage,"Cosmos Big-Data \n Analytics GE",component)    
            note right of wcge
                wgt
            end note
            wcge -> cbdage
            wcge <- cbdage
            imkge -[hidden]right- wcge
            cbdage -[hidden]right- wcge
        }
        skinparam shadowing false
        skinparam rectangleBorderColor white
        rectangle "<font color=white> r" as tdown{
            FIWARE(ocbge,"Orion Context \n Broker GE",component)
            FIWARE(cc,"Cygnus \n Connector",component) 
            cc <- ocbge
        }
        rhd -[hidden]down- tdown
        imkge -> cc
        imkge <- cc
    }

    node "[Collection of data]" as cof{
        [NGSI & oHealth-Context] as ngsihc
        rectangle "<font color=white>r" as inner{
            [Fitbit] as fit
            [SmartWatch] as smartw
            [SmartPhone] as smartp
            smartp -[hidden]left- smartw
            smartw -[hidden]left- fit
        }
        ngsihc -[hidden]down- inner

        ngsihc <-- fit
        ngsihc <-- smartw
        ngsihc <-- smartp
    }

    ocbge -[hidden]down- ngsihc
    ngsihc --> ocbge
@enduml