'Environment Monitoring Pattern
@startuml
    skinparam componentStyle uml2

    !define ICONURL https://raw.githubusercontent.com/smartsdk/architecture-diagrams/smartsdk-template/dist
    !includeurl ICONURL/common.puml
    !includeurl ICONURL/fiware.puml
    !includeurl ICONURL/smartsdk.puml


    skinparam shadowing false
    skinparam rectangleBorderColor white
    rectangle "<font color=white>top" as top{
      SMARTSDK(fesca, "FrontEnd Smart City Application", component)
      SMARTSDK(besca, "BackEnd Smart City Application", component)
      SMARTSDK(maall, "Mobile Alert Application for accidents, \n traffic jam, pollution, weather \conditon, pollen, asthma attacks", component)
      fesca -[hidden]right- besca
      besca -[hidden]right- maall
    }

      rectangle "<font color=white>mid" as mid {
        FIWARE(cbo, "Context Broker \n -Orion", component)
        package "IoT Backed" as iotb{
          FIWARE(iotbr, "IoT Broker", component)
          FIWARE(iotd, "IoT Discovery", component)
          FIWARE(bedmi, "Backend device management \n IDAS", component)
        }
        
        interface "COAP" as coap 
        cloud "Cloudino \n cloud" as ccloudino   
        interface "MQTT" as mqtt
        interface "LWM2M" as lwm2m      
        
        cbo -[hidden]down- iotb
        
        iotb -[hidden]down- lwm2m
        mid -[hidden]down- mqtt
        ccloudino -- coap
        ccloudino -- mqtt
      }

      rectangle "<font color=white>mid" as rdown {
        package "SDK library for NGSI" as sdklfngsi{
          SMARTSDK(sensors, "Mobile device \n (location)", component)
        }
        package "IoT Device" as piotd{
          SMARTSDK(cloudino, "Cloudino", component)
          [Humidity sensor] as hs
          [Temperature sensor] as ts
          [GPS sensor (in progress)] as gpssdev
          cloudino -- hs
          cloudino -- gpssdev
          cloudino - ts
        }
      }
      
    package "Iot Fixed Device" as iotfd{
          SMARTSDK(ssp, "Smart spot", component)
          [Gas detection sensor \n NO2, SO2, CO, O3] as gds2
          [Temperature and humidity sensor] as tahs2
          [GPS Sensor in progress] as gpss
          ssp -- gds2
          ssp -- tahs2
          ssp -- gpss
    }
    sdklfngsi -[hidden]right- iotd

    FIWARE(imk, "Identity Manager \n (Keyrock)", component)
    interface "Oauth 2" as oau2
    interface "NGSI" as ngsi  
  
      package "Cosmos (to be developed)" as ctbd{
        FIWARE(cygnus, "Cygnus", component)
        FIWARE(bdan, "Big Data Analysis", component)
        FIWARE(sthc, "STH commet", component)
        cygnus -- sthc
        cygnus -- bdan
      }

      package "IoT Mobile Device" as iotmd{
          SMARTSDK(spot, "Smart Spot", component)
          '[Smart Spot] as spot
          [Gas detection sensor \n NO2, SO2, CO, O3] as gds
          [Temperature and humidity sensor] as tahs
          [GPS sensor \n (in progress)] as gpssip
          spot - gds
          spot -- gpssip
          spot -- tahs
      }

    fesca -- oau2
    imk -- oau2

    fesca -- ngsi
    besca -- ngsi
    cbo -- ngsi
    maall -- ngsi
    iotd -- ngsi
    cygnus --ngsi
    sensors -- ngsi
    cloudino -- ngsi
    bedmi -- ngsi

    bedmi -- coap
    bedmi -- mqtt
    bedmi -- lwm2m

    ssp -- lwm2m
    spot -- lwm2m
    ngsi -- cloudino
    ccloudino -- cloudino 
    
    
    'agrupamiento de componentes
    oau2 -[hidden]down- mid
    mqtt -[hidden]down- iotfd
    mqtt -[hidden]down- iotmd
    sdklfngsi -[hidden]down- iotd
    

@enduml